# @package _global_
defaults:
  - metrics@metrics.kormedmcqa_dentist: mcq_accuracy
  - metrics@metrics.kormedmcqa_doctor: mcq_accuracy
  - metrics@metrics.kormedmcqa_nurse: mcq_accuracy
  - metrics@metrics.kormedmcqa_pharm: mcq_accuracy
  - metrics/aggregator@score_aggregators.kormedmcqa_dentist: default
  - metrics/aggregator@score_aggregators.kormedmcqa_doctor: default
  - metrics/aggregator@score_aggregators.kormedmcqa_nurse: default
  - metrics/aggregator@score_aggregators.kormedmcqa_pharm: default
  - metrics/aggregator@score_aggregators.kormedmcqa: weighted_avg

datasets:
  kormedmcqa:
    kormedmcqa_dentist:
      _target_: coeval.datasets.kormedmcqa.KorMedMCQADentistDataset
      num_samples: ${num_samples}
      system_prompt: ${system_prompt}

    kormedmcqa_doctor:
      _target_: coeval.datasets.kormedmcqa.KorMedMCQADoctorDataset
      num_samples: ${num_samples}
      system_prompt: ${system_prompt}

    kormedmcqa_nurse:
      _target_: coeval.datasets.kormedmcqa.KorMedMCQANurseDataset
      num_samples: ${num_samples}
      system_prompt: ${system_prompt}

    kormedmcqa_pharm:
      _target_: coeval.datasets.kormedmcqa.KorMedMCQAPharmDataset
      num_samples: ${num_samples}
      system_prompt: ${system_prompt}
